---
title: "Stats Modeling Project"
author: "Group 5: Xin Jin, Reid Ginoza, Heidi Lovejoy"
date: "11/18/2019"
output: pdf_document
bibliography: bibliography.bib
nocite: | 
  @rlang
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(kableExtra) # for tables
library(magrittr)  # provides more pipe oeprators
library(haven)
options(knitr.table.format = "latex")
```

```{r import data}
institution_data <- read_spss('InstLevel.sav') %>%
  select(  # will change later when we decide what variables we want
  -unitid, -addr1_txt, -addr2_txt, -city_txt, -zip_text, -sector_cd, -ClassificationCode, -ClassificationOther
  ) %>%
  filter(grepl('4-year', sector_name))  %>% # only 4-year Schools
  filter(is.na(IL_PARTIC_COED_MEN) | IL_PARTIC_COED_MEN == 0 ) %>% # only schools with no male participants in coed
  filter(is.na(IL_PARTIC_COED_WOMEN) | IL_PARTIC_COED_WOMEN == 0 ) %>% # only schools with no female participants in coed
  select(-contains("COED")) # ignore variables with the word "coed"

```

```{r Notes to self, include=FALSE}
# To view the school data
# school_data <- read_spss('Schools.sav') %>% select(
#   -unitid, -addr1_txt, -addr2_txt, -zip_text, -ClassificationCode,-ClassificationOther,
#   -sector_cd
#   )

# To view variables included as a list (although you could probably just view the data):
# institution_columns <- institution_data %>% colnames()

# To view number of NAs in a column:
# count.of.na <- institution_data %>% summarise_all(~sum(is.na(.)))
```

# Introduction



## Session Info
```{r Session Info}
sessionInfo()
```

# References