---
title: "Stats Modeling Project"
author: "Group 5: Xin Jin, Reid Ginoza, Heidi Lovejoy"
date: "11/18/2019"
# header-includes:
#    - \usepackage{amsmath, amssymb}
   # - \usepackage{natbib}
   # - \usepackage{hyperref}
output: pdf_document
bibliography: bibliography.bib
nocite: | 
  @rlang
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pgirmess)
library(pander)
library(tidyverse)
library(knitr)
library(kableExtra) # for tables
library(magrittr)  # provides more pipe oeprators
library(haven)
options(knitr.table.format = "latex")
```

```{r support functions}
almost_sas <- function(aov.results){
  par(mfrow=c(2,2))
  plot(aov.results, which=1)
  plot(aov.results, which=2)
  aov_residuals <- residuals(aov.results)
  plot(density(aov_residuals))
  hist(aov_residuals)
}
```

```{r import data, echo=FALSE}
institution_data <- read_spss('InstLevel.sav') %>%
  select(institution_name, state_cd, ClassificationCode, Classification=classification_name, sector_cd, sector_name, HDCOACH_SALARY_MEN, HDCOACH_SALARY_WOMEN, IL_PARTIC_MEN, IL_PARTIC_WOMEN, IL_PARTIC_COED_MEN, IL_PARTIC_COED_WOMEN) %>%
  filter(grepl('4-year', sector_name))  %>% # only 4-year Schools
  filter(is.na(IL_PARTIC_COED_MEN) | IL_PARTIC_COED_MEN == 0 ) %>% # only schools with no male participants in coed
  filter(is.na(IL_PARTIC_COED_WOMEN) | IL_PARTIC_COED_WOMEN == 0 ) %>% # only schools with no female participants in coed
  select(-contains("COED")) %>% # ignore variables with the word "coed"
  filter(!is.na(HDCOACH_SALARY_MEN)) %>% # filter out NA
  filter(!is.na(HDCOACH_SALARY_WOMEN)) %>% # filter out NA
  type.convert()  # makes ints and factors

ncaa.div.i_data <- institution_data %>%
  filter(grepl('NCAA Division I-', Classification)) # only NCAA division 1

men_data <- institution_data %>%
  select(-contains("WOMEN")) %>% 
  rename(Salary = HDCOACH_SALARY_MEN, Participation = IL_PARTIC_MEN)

women_data <- institution_data %>%
  select(-contains("_MEN")) %>%
  rename(Salary = HDCOACH_SALARY_WOMEN, Participation = IL_PARTIC_WOMEN)

gender.separated_data <- bind_rows(
  men_data %>% add_column(Gender = "Men"),
  women_data %>% add_column(Gender = "Women")
)
```

# Almost SAS
```{r twoway ANOVA interaction between classification and gender}
classification.gender.interaction.results <- gender.separated_data %$% 
  aov(Salary ~ Classification * Gender)
interaction.summary <- classification.gender.interaction.results %>% summary()
interaction.resid <- tibble(Residuals=(classification.gender.interaction.results %>% residuals()))
```



```{r}
residual.plot <- classification.gender.interaction.results %>%
  ggplot(aes(x = .fitted, y = .resid)) +
  geom_point() +
  geom_hline(yintercept = 0, color = 'red') + 
  ggtitle("Residuals vs. Fitted") +
  theme_bw() + 
  scale_y_continuous(labels = scales::scientific)

qq.plot <- interaction.resid %>% ggplot(aes(sample = Residuals)) +
  stat_qq() + stat_qq_line(color = 'red') + scale_y_continuous(labels = scales::scientific) +
  theme_bw() + ggtitle("Q-Q Plot of Residuals")

bw <- 2 * IQR(interaction.resid$Residuals) / length(interaction.resid$Residuals)^(1/3)

histogram.resid <- interaction.resid %>% ggplot(aes(x=Residuals)) +
  geom_histogram(binwidth = bw) +
  ggtitle("Histogram of Residuals") + 
  scale_x_continuous(labels = scales::scientific) +
  theme_bw()
histogram.resid

density.resid <- interaction.resid %>% ggplot(aes(x=Residuals)) +
  geom_density() +
  ggtitle("Density Plot of Residuals") + 
  theme_bw()

cowplot::plot_grid(residual.plot, qq.plot, histogram.resid, density.resid)
```
```{r}
classification.gender.interaction.results %>% almost_sas()
```


```{r Notes to self, include=FALSE}
##### All 4-year Institutions
# institution_data <- read_spss('InstLevel.sav') %>%
#   select(  # TODO will change later when we decide what variables we want
#   -unitid, -addr1_txt, -addr2_txt, -city_txt, -zip_text, -sector_cd,
#   -ClassificationCode, -ClassificationOther
#   ) %>%
#   filter(grepl('4-year', sector_name))  %>% # only 4-year Schools
#   filter(is.na(IL_PARTIC_COED_MEN) | IL_PARTIC_COED_MEN == 0 ) %>% # only schools with no male participants in coed
#   filter(is.na(IL_PARTIC_COED_WOMEN) | IL_PARTIC_COED_WOMEN == 0 ) %>% # only schools with no female participants in coed
#   select(-contains("COED")) # ignore variables with the word "coed"

##### To view the school data
# school_data <- read_spss('Schools.sav') %>% select(
#   -unitid, -addr1_txt, -addr2_txt, -zip_text, -ClassificationCode,-ClassificationOther,
#   -sector_cd
#   )

#####
# To view variables included as a list (although you could probably just view the data):
# institution_columns <- institution_data %>% colnames()

#####
# To view number of NAs in a column:
# count.of.na <- institution_data %>% summarise_all(~sum(is.na(.)))

#####
# To view unique entries of a column
# divisions <- institution_data$classification_name %>% unique()
```

# Notes for Kruskal-Wallis posthoc comparison 
```{r}
classification.kw.posthoc <- gender.separated_data %$% kruskalmc(Salary ~ Classification)
classification.kw.posthoc[[3]] %>% as_tibble(rownames = "Comparison") -> classification.pairwise.comparisons
```


# Counts of Divisions
```{r count}
institution_data %>%
  group_by(Classification) %>% 
  summarize('Mean Men Head Coach Salary'=mean(HDCOACH_SALARY_MEN), 'SD Men'=sd(HDCOACH_SALARY_MEN),  
            'Mean Woen Head Coach Salary'=mean(HDCOACH_SALARY_WOMEN), 'SD Women'=sd(HDCOACH_SALARY_WOMEN), Count=n()) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover"),
                full_width = F,
                font_size = 14,
                position = "left")
```



```{r Classification Codes}
institution_data %>%
  select(ClassificationCode, Classification) %>%
  unique()
```

```{r}
institution_data %>%
  filter(ClassificationCode==9) %>%
  select(Classification,HDCOACH_SALARY_WOMEN) %>%
  # summarize(mean=mean(HDCOACH_SALARY_MEN)) # results in NA
  summary()
```

```{r}
two.way.anova.attempt <- institution_data %>%
  select(Classification, HDCOACH_SALARY_MEN, HDCOACH_SALARY_WOMEN) %>%
  gather("Gender", "Salary", -Classification)
two.way.anova.attempt$Gender %<>% recode(HDCOACH_SALARY_MEN="Men", HDCOACH_SALARY_WOMEN="Women")
two.way.anova.attempt
```

```{r}
adv_aov.results <- aov(Salary ~ Classification*Gender, data = two.way.anova.attempt)
adv_aov.table <- adv_aov.results %>% summary()
adv_aov.table %>% pander(style = 'rmarkdown')
```

# Results
<!-- %TODO Describe the data (1st paragraph) -->


## Describing and Visualizing Head Coach data
```{r hist of head coach, message=FALSE}
hd.coach.salary_data <- ncaa.div.i_data %>%
  select(sector_name, HDCOACH_SALARY_MEN)

hd.coach.salary_data %>%
  ggplot(aes(x = HDCOACH_SALARY_MEN, fill = sector_name)) +
  geom_histogram(position = "dodge") +
  labs(title="Histogram of NCAA Div. I Men's Head Coach Salary", x = "Salary (USD)",
       y = "Count", fill = "School Type:") +
  theme(
    legend.position="bottom",
    panel.background = element_rect(fill = 'white', color = 'grey'),
    panel.grid.major = element_line(size = 0.25, linetype = 'solid',
                                color = "grey"), 
    panel.grid.minor = element_line(size = 0.1, linetype = 'solid',
                                color = "grey")
  )
```

```{r qq plot of Private Schools head coach}
hd.coach.salary_data %>%
  filter(grepl('Private', sector_name)) %>% 
  ggplot(aes(sample = HDCOACH_SALARY_MEN)) + 
  stat_qq() + stat_qq_line() + theme_bw()
```
```{r qq plot Public Schools head cach}
hd.coach.salary_data %>%
  filter(grepl('Public', sector_name)) %>% 
  ggplot(aes(sample = HDCOACH_SALARY_MEN)) + 
  stat_qq() + stat_qq_line() + theme_bw()
```

## Describing and Visualizing Participation of Men and Head Coach Salaries
```{r scatter plot of head coach salaries}
men.participation.data <- ncaa.div.i_data %>%
  select(IL_PARTIC_MEN, HDCOACH_SALARY_MEN)

men.participation.data %>% ggplot(aes(x=IL_PARTIC_MEN, y=HDCOACH_SALARY_MEN)) +
  geom_point() +
  geom_smooth(method = lm) +
  labs(title="Scatterplot of Men's Head Coach Salary by Men Particiation Counts", x = "Count of Men Participating",
       y = "Head Coach's Salary (USD)") +
  theme(
    panel.background = element_rect(fill = 'white', color = 'grey'),
    panel.grid.major = element_line(size = 0.25, linetype = 'solid',
                                color = "grey"), 
    panel.grid.minor = element_line(size = 0.1, linetype = 'solid',
                                color = "grey")
  )
```


# References